### PR TITLE
Disable NibLoadingInternal Functions

### PR DESCRIPTION
**Pull request by TheBrokenRail**
These can be re-enabled when the are implemented.

Related to darlinghq/darling#659

### CODE REVIEW

**Comment by bugaevc** [comment]
Why do you write a nice PR description but a poor commit message instead of the other way around? :(

That is to say, please fix the commit message.

**Comment by bugaevc** [comment]
Don't forget to include a link to the issue (but don't say it closes or fixes it — "works around" or "helps with" are appropriate)

**Comment by TheBrokenRail** [comment]
@bugaevc Done!

**Comment by TheBrokenRail** [comment]
@bugaevc Any updates?

**Comment by TheBrokenRail** [comment]
@LubosD Now that these are implemented this should be reverted.

**Comment by bugaevc** [comment]
Hold on for a bit, that implementation is not quite correct.

**Pull request merged**
